###################################################################################################
# This Vagrantfile derives from the original (https://github.com/apache/incubator-openwhisk/blob/master/tools/vagrant/Vagrantfile)
# and deploys OpenWhisk into a single AWS VM.  It is dependent on the AWS Vagrant plug in:
#
# https://github.com/mitchellh/vagrant-aws
#
# As such, before you try to use this file, you need to do the following to install the plugin:
#
# vagrant plugin install vagrant-aws
#
# And then tell Vagrant about the dummy AWS box:
#
# vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
#
# Further, this file requires the following environment variables be set to drive its behavior:
#
# ACCESS_KEY_ID - The AWS access key for the account you'd like to deploy OpenWhisk to
# SECRET_ACCESS_KEY - The AWS secret key for the account you'd like to deploy OpenWhisk to
# KEYPAIR_NAME - The name of the keypair from the AWS console used to SSH into the resulting VM
# PRIVATE_KEY_PATH - Full path to the .pem file for the keypair.  ie: "~/.ssh/fred.pem"
# AWS_REGION - Name of AWS region to deploy to.  ie: "us-west-2"
# AWS_AMI - Name of the AMI used to create the VM.  ie: "ami-d94f5aa0"
# AWS_INSTANCE_TYPE - Name of AWS instance type used to create the VM.  ie: "t2.small" >= t2.small please
# AWS_SECURITY_GROUP_ID - ID (not name) of the security group applied to the VM.  ie: "sg-XXXXXXXX"
# AWS_SUBNET_ID - ID of the subnet within the VPC the VM should be created in.  ie: "subnet-XXXXXXX"
#
# Be sure to set up the Security Group in such a way that all the ports for OpenWhisk are open should
# you want to ping the individual services.  The instance type name MUST be t2.small or greater or
# else the Kafka and Controller components become memory starved.  This will be improved at a later date.
#
###################################################################################################

# Require the AWS provider plugin
require 'vagrant-aws'

MACHINE_IP = '127.0.0.1'

# Create and configure the AWS instance(s)
Vagrant.configure('2') do |config|

  # Use dummy AWS box
  config.vm.box = 'aws-dummy'

  # Specify AWS provider configuration
  config.vm.provider 'aws' do |aws, override|
    # Read AWS authentication information
    aws.access_key_id = ENV['ACCESS_KEY_ID']
    aws.secret_access_key = ENV['SECRET_ACCESS_KEY']

    # Specify SSH keypair to use
    aws.keypair_name = ENV['KEYPAIR_NAME']

    # Specify region, AMI ID, and security group(s)
    aws.region = ENV['AWS_REGION']
    aws.ami = ENV['AWS_AMI']
    aws.security_groups = [ENV['AWS_SECURITY_GROUP_ID']]
    aws.instance_type = ENV['AWS_INSTANCE_TYPE']
	aws.subnet_id = ENV['AWS_SUBNET_ID']
	aws.associate_public_ip = true
	
	# Specify disk volume size
	aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 12 }]

    # Specify username and private key path
    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = ENV['PRIVATE_KEY_PATH']
  end

  # Prevents "stdin: is not a tty" on Ubuntu (https://github.com/mitchellh/vagrant/issues/1673)
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

end